language: objective-c
os: osx
osx_image: xcode8.2
xcode_sdk: iphoneos10.2
xcode_workspace: ChatApp.xcworkspace
xcode_scheme: ChatApp
before_install:
  - gem install cocoapods
  before_script:
- ./scripts/travis/add-key.sh
script: xctool -workspace ChatApp.xcworkspace -scheme ChatApp -sdk iphoneos10.2 ONLY_ACTIVE_ARCH=NO  CONFIGURATION_BUILD_DIR='~/build/'  build
after_script:
- ./scripts/travis/remove-key.sh
